### ISSUE TITLE
Requirement is pinned for mitemp-bt 0.0.3: btlewrap==0.0.8

### ISSUE THREAD

**Issue by MartinHjelmare** [ratcashdev/mitemp#20]
- This library supports an integration in Home Assistant.
- The upcoming pip resolver will be more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.

Thanks for your support of Home Assistant!

**Comment by tinstep** [comment]
I just go this on KDE Neon.
`mitemp-bt 0.0.3 requires btlewrap==0.0.8, but you'll have btlewrap 0.0.10 which is incompatible.`
`miflora 0.6 requires btlewrap==0.0.8, but you'll have btlewrap 0.0.10 which is incompatible.`

I'll try a
`pip install 'btlewrap==0.0.8' --force-reinstall`
but it would be nice if a minimum version was spec'd rather than an absolute version.

**Comment by fabaff** [comment]
Also an issue for the Fedora RPM package. The Fedora Package Collection already has `btlewrap0.0.10` and the pinning makes an installation fails.

Thanks

**Comment by onkelbeh** [comment]
same here.

**Comment by ratcashdev** [comment]
Sorry guys, anyone willing to create a PR?

**Comment by onkelbeh** [comment]
Could do it, reluctanty, because I cannot test without hardware. Just replace these two == with >=, update btlewrap to a current version and test it.
